/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  FlashLoanReceiverBase,
  FlashLoanReceiverBaseInterface,
} from "../../../../core-v3/flashloan/base/FlashLoanReceiverBase";

const _abi = [
  {
    inputs: [],
    name: "ADDRESSES_PROVIDER",
    outputs: [
      {
        internalType: "contract IPoolAddressesProvider",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "POOL",
    outputs: [
      {
        internalType: "contract IPool",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "assets",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "amounts",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "premiums",
        type: "uint256[]",
      },
      {
        internalType: "address",
        name: "initiator",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "params",
        type: "bytes",
      },
    ],
    name: "executeOperation",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class FlashLoanReceiverBase__factory {
  static readonly abi = _abi;
  static createInterface(): FlashLoanReceiverBaseInterface {
    return new Interface(_abi) as FlashLoanReceiverBaseInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): FlashLoanReceiverBase {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as FlashLoanReceiverBase;
  }
}
