export enum INTENTS {
  INTENT_DEPOSIT = 'INTENT_DEPOSIT',
  INTENT_BORROW = 'INTENT_BORROW',
  INTENT_SWAP = 'INTENT_SWAP',
  INTENT_FARM = 'INTENT_FARM',
  INTENT_AUTOCOMPOUND = 'INTENT_AUTOCOMPOUND',
  INTENT_AUTOREBALANCE = 'INTENT_AUTOREBALANCE',
  INTENT_STOPLOSS = 'INTENT_STOPLOSS',
}

export enum INTENTS_INPUT {
  INTENTS_INPUT_TOKENS = 'INTENTS_INPUT_TOKENS',
  INTENTS_INPUT_LEVERAGE = 'INTENTS_INPUT_LEVERAGE',
  INTENTS_INPUT_PRICE_RANGE = 'INTENTS_INPUT_PRICE_RANGE',
  INTENTS_INPUT_STOPLOSS_RANGE = 'INTENTS_INPUT_STOPLOSS_RANGE',
}

export const isMonitor = (intent: INTENTS) => {
  return [INTENTS.INTENT_AUTOCOMPOUND, INTENTS.INTENT_AUTOREBALANCE, INTENTS.INTENT_STOPLOSS].includes(intent)
}

export const INTENT_MAP = {
  [INTENTS.INTENT_DEPOSIT]: {
    method: 'Deposit',
    params: [INTENTS_INPUT.INTENTS_INPUT_TOKENS],
  },
  [INTENTS.INTENT_BORROW]: {
    method: 'Borrow',
    params: [INTENTS_INPUT.INTENTS_INPUT_TOKENS],
  },
  [INTENTS.INTENT_SWAP]: {
    method: 'Swap',
    params: [INTENTS_INPUT.INTENTS_INPUT_TOKENS],
  },
  [INTENTS.INTENT_FARM]: {
    method: 'Farm',
    params: [INTENTS_INPUT.INTENTS_INPUT_TOKENS, INTENTS_INPUT.INTENTS_INPUT_PRICE_RANGE],
  },
  [INTENTS.INTENT_AUTOCOMPOUND]: {
    method: 'AutoCompound',
    params: [],
  },
  [INTENTS.INTENT_AUTOREBALANCE]: {
    method: 'AutoRebalance',
    params: [],
  },
  [INTENTS.INTENT_STOPLOSS]: {
    method: 'Stoploss',
    params: [INTENTS_INPUT.INTENTS_INPUT_STOPLOSS_RANGE],
  },
}
