export enum INTENTS {
  INTENT_DEPOSIT = 'INTENT_DEPOSIT',
  INTENT_BORROW = 'INTENT_BORROW',
  INTENT_SWAP = 'INTENT_SWAP',
  INTENT_FARM = 'INTENT_FARM',
  INTENT_AUTOCOMPOUND = 'INTENT_AUTOCOMPOUND',
  INTENT_AUTOREBALANCE = 'INTENT_AUTOREBALANCE',
  INTENT_RANGESTOP = 'INTENT_RANGESTOP',
}

export enum INTENTS_INPUT {
  INTENTS_INPUT_TOKENS = 'INTENTS_INPUT_TOKENS',
  INTENTS_INPUT_LEVERAGE = 'INTENTS_INPUT_LEVERAGE',
  INTENTS_INPUT_PRICE_RANGE = 'INTENTS_INPUT_PRICE_RANGE',
  INTENTS_INPUT_RANGESTOP_RANGE = 'INTENTS_INPUT_RANGESTOP_RANGE',
}

export const isMonitor = (intent: INTENTS) => {
  return [INTENTS.INTENT_AUTOCOMPOUND, INTENTS.INTENT_AUTOREBALANCE, INTENTS.INTENT_RANGESTOP].includes(intent)
}

export const INTENT_MAP = {
  [INTENTS.INTENT_DEPOSIT]: {
    method: 'Deposit',
    params: [INTENTS_INPUT.INTENTS_INPUT_TOKENS],
  },
  [INTENTS.INTENT_BORROW]: {
    method: 'Borrow',
    params: [INTENTS_INPUT.INTENTS_INPUT_TOKENS],
  },
  [INTENTS.INTENT_SWAP]: {
    method: 'Swap',
    params: [INTENTS_INPUT.INTENTS_INPUT_TOKENS],
  },
  [INTENTS.INTENT_FARM]: {
    method: 'Farm',
    params: [INTENTS_INPUT.INTENTS_INPUT_TOKENS, INTENTS_INPUT.INTENTS_INPUT_PRICE_RANGE],
  },
  [INTENTS.INTENT_AUTOCOMPOUND]: {
    method: 'AutoCompound',
    params: [],
  },
  [INTENTS.INTENT_AUTOREBALANCE]: {
    method: 'AutoRebalance',
    params: [],
  },
  [INTENTS.INTENT_RANGESTOP]: {
    method: 'RangeStop',
    params: [INTENTS_INPUT.INTENTS_INPUT_RANGESTOP_RANGE],
  },
}
