/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as extraXAccountFactorySol from "./ExtraXAccountFactory.sol";
export type { extraXAccountFactorySol };
