export interface PoolBaseCurrencyHumanized {
  marketReferenceCurrencyDecimals: number
  marketReferenceCurrencyPriceInUsd: string
  networkBaseTokenPriceInUsd: string
  networkBaseTokenPriceDecimals: number
}
export interface ReserveDataHumanized {
  id: string
  underlyingAsset: string
  name: string
  symbol: string
  decimals: number
  baseLTVasCollateral: string
  reserveLiquidationThreshold: string
  reserveLiquidationBonus: string
  reserveFactor: string
  usageAsCollateralEnabled: boolean
  borrowingEnabled: boolean
  stableBorrowRateEnabled: boolean
  isActive: boolean
  isFrozen: boolean
  liquidityIndex: string
  variableBorrowIndex: string
  liquidityRate: string
  variableBorrowRate: string
  stableBorrowRate: string
  lastUpdateTimestamp: number
  aTokenAddress: string
  stableDebtTokenAddress: string
  variableDebtTokenAddress: string
  interestRateStrategyAddress: string
  availableLiquidity: string
  totalPrincipalStableDebt: string
  averageStableRate: string
  stableDebtLastUpdateTimestamp: number
  totalScaledVariableDebt: string
  priceInMarketReferenceCurrency: string
  priceOracle: string
  variableRateSlope1: string
  variableRateSlope2: string
  stableRateSlope1: string
  stableRateSlope2: string
  baseStableBorrowRate: string
  baseVariableBorrowRate: string
  optimalUsageRatio: string
  // v3 only
  isPaused: boolean
  isSiloedBorrowing: boolean
  accruedToTreasury: string
  unbacked: string
  isolationModeTotalDebt: string
  debtCeiling: string
  debtCeilingDecimals: number
  eModeCategoryId: number
  borrowCap: string
  supplyCap: string
  eModeLtv: number
  eModeLiquidationThreshold: number
  eModeLiquidationBonus: number
  eModePriceSource: string
  eModeLabel: string
  borrowableInIsolation: boolean
  flashLoanEnabled: boolean
  virtualAccActive: boolean
  virtualUnderlyingBalance: string
}
