export const ADDRESS_ID_WETH = 1

export const ADDRESS_ID_EXTRA_PROXY_UPDATE_CONTROLLER = 101
export const ADDRESS_ID_EXTRA_ADMIN_CONTROL = 102
export const ADDRESS_ID_EXTRA_TREASURY = 103

export const ADDRESS_ID_UNISWAP_V3_FACTORY = 501
export const ADDRESS_ID_UNISWAP_V3_ROUTER = 502
export const ADDRESS_ID_UNISWAP_V3_POS_MANAGER = 503

export const ADDRESS_ID_EXTRA_X_ORACLE_MANAGER = 1001
export const ADDRESS_ID_PRICE_FEED_CHAINLINK = 1002
export const ADDRESS_ID_PRICE_FEED_UNISWAP_V3 = 1003

export const ADDRESS_ID_EXTRA_X_ACCOUNT_SINGLETON = 2001
export const ADDRESS_ID_EXTRA_X_ACCOUNT_FACTORY = 2002

export const ADDRESS_ID_EXTRA_X_LENDINGPOOL = 3001
export const ADDRESS_ID_EXTRA_X_Lending_E_TOKEN_IMPL = 3002
export const ADDRESS_ID_EXTRA_X_Lending_DEBT_TOKEN_IMPL = 3003

export const ADDRESS_ID_EXTRA_X_HEALTH_MANAGER = 4001
export const ADDRESS_ID_EXTRA_X_UNDERLYING_TOKENS_E_TOKEN = 4002
export const ADDRESS_ID_EXTRA_X_UNDERLYING_TOKENS_DEBT_TOKEN = 4003
export const ADDRESS_ID_EXTRA_X_UNDERLYING_TOKENS_UNI_V3_POS = 4004

export const ADDRESS_ID_EXTRA_X_TRANSACTION_FILTER = 5001
export const ADDRESS_ID_EXTRA_X_FUNC_FILTER_HEALTH_MANAGER = 5002
export const ADDRESS_ID_EXTRA_X_FUNC_FILTER_LENDING = 5003
export const ADDRESS_ID_EXTRA_X_FUNC_FILTER_ERC20 = 5004
export const ADDRESS_ID_EXTRA_X_FUNC_FILTER_UNI_V3_PM = 5005
export const ADDRESS_ID_EXTRA_X_FUNC_FILTER_UNI_V3_ROUTER = 5006
